
/**
 * Detailed description of the class.
 *
 * @author Sun Rui
 * @date 2025-10-08
 * @version 2.0
 */

package sg.com.aori.controller;

import java.net.URI;
import java.util.List;
import java.util.Optional;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import sg.com.aori.model.Customer;
import sg.com.aori.model.CustomerAddress;
import sg.com.aori.interfaces.ICreateAccount;

/**
 * REST controller for the "Create Account" use case.
 * Endpoints focus on creating a Customer and (optionally) adding an initial
 * CustomerAddress.
 */
@RestController
@RequestMapping("/api/customers") 
// YC's comment: can change this to "/api/account"), then when creating account use, map to "/api/account/register"
public class CustomerController {

    /** Service handling the Create Account use case */
    private final ICreateAccount createAccountService;

    public CustomerController(ICreateAccount createAccountService) {
        this.createAccountService = createAccountService;
    }

    /**
     * Create a new customer.
     *
     * param: customer Request body containing a fully-prepared Customer entity (id
     * auto-generated by entity).
     * return: 201 Created with the persisted Customer in body and Location header
     * pointing to /api/customers/{id}.
     * throws: IllegalArgumentException if input is invalid.
     */
    @PostMapping
    public ResponseEntity<Customer> createCustomer(@RequestBody Customer customer) {
        Customer saved = createAccountService.createCustomer(customer);
        return ResponseEntity
                .created(URI.create("/api/customers/" + saved.getCustomerId()))
                .body(saved);
    }

    /**
     * Get a customer by id.
     *
     * param: customerId The Customer primary key (String UUID).
     * return: 200 OK with Customer if found, otherwise 404 Not Found.
     * throws: IllegalArgumentException if input is invalid.
     */
    @GetMapping("/{customerId}")
    public ResponseEntity<Customer> getCustomerById(@PathVariable String customerId) {
        Optional<Customer> opt = createAccountService.getCustomerById(customerId);
        return opt.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    /**
     * Get a customer by email.
     *
     * param: email Email address to search for (as query parameter).
     * return: 200 OK with Customer if found, otherwise 404 Not Found.
     * throws: IllegalArgumentException if input is invalid.
     */
    @GetMapping
    public ResponseEntity<Customer> getCustomerByEmail(@RequestParam("email") String email) {
        Optional<Customer> opt = createAccountService.getCustomerByEmail(email);
        return opt.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    /**
     * Add an initial address for the given customer.
     * If the customer has no default address yet, this address will be marked as
     * default.
     *
     * param: customerId The Customer primary key (String UUID) from the path.
     * param: address The address payload; its customerId will be enforced to match path variable.
     * return: 201 Created with the persisted CustomerAddress in body and Location
     * header pointing to /api/customers/{id}/addresses.
     * throws: IllegalArgumentException if input is invalid.
     */
    @PostMapping("/{customerId}/addresses")
    public ResponseEntity<CustomerAddress> addInitialAddress(@PathVariable String customerId,
            @RequestBody CustomerAddress address) {
        // 以路径变量为准，避免与 body 内不一致
        address.setCustomerId(customerId);
        CustomerAddress saved = createAccountService.addInitialAddress(address);
        return ResponseEntity
                .created(URI.create("/api/customers/" + customerId + "/addresses"))
                .body(saved);
    }

    /**
     * List all addresses of a customer (newest first).
     *
     * param: customerId The Customer primary key (String UUID).
     * return: 200 OK with a list of CustomerAddress ordered by createdAt descending
     * (possibly empty).
     * throws: IllegalArgumentException if input is invalid.
     */
    @GetMapping("/{customerId}/addresses")
    public ResponseEntity<List<CustomerAddress>> listAddresses(@PathVariable String customerId) {
        List<CustomerAddress> list = createAccountService.listAddresses(customerId);
        return ResponseEntity.ok(list);
    }
}
