package sg.com.aori.controller;

import java.net.URI;
import java.util.Optional;
import jakarta.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import sg.com.aori.interfaces.ICreateAccount;
import sg.com.aori.model.Customer;
import sg.com.aori.model.CustomerAddress;
import sg.com.aori.service.CustomerService;

/**
 * Use uuid to get instead of email
 * 
 * @author Sun Rui
 * @date 2025-10-08
 * @version 1.3
 */

@CrossOrigin
@RestController
@RequestMapping("/api/customers")
public class CustomerController {

    private final ICreateAccount createAccountService;

    private final CustomerService customerService;

    public CustomerController(ICreateAccount createAccountService, CustomerService customerService) {
        this.createAccountService = createAccountService;
        this.customerService = customerService;
    }

    /**
     * Create a new customer.
     * 
     * @param customer Request body containing a fully-prepared Customer entity (id
     *                 auto-generated by entity).
     * @return 201 Created with the persisted Customer in body and Location header
     *         pointing to /api/customers/{id}.
     * @throws IllegalArgumentException if input is invalid.
     */
    @PostMapping
    public ResponseEntity<Customer> createCustomer(@Valid @RequestBody Customer customer) {
        if (customer.getCustomerId() == null || customer.getCustomerId().isBlank()) {
            customer.setCustomerId(java.util.UUID.randomUUID().toString());
        }
        Customer saved = createAccountService.createCustomer(customer);
        return ResponseEntity
                .created(URI.create("/api/customers/" + saved.getCustomerId()))
                .body(saved);
    }

    /**
     * Get a customer by id from query parameter.
     * 
     * @param customerId
     * @return
     */
    @GetMapping
    public ResponseEntity<Customer> getCustomerByIdQuery(@RequestParam("customerId") String customerId) {
        return buildCustomerResponse(customerService.findCustomerById(customerId));
    }

    /**
     * Add an initial address for the given customer.
     * If the customer has no default address yet, this address will be marked as
     * default.
     *
     * @param customerId The Customer primary key (String UUID) from the path.
     * @param address    The address payload; its customerId will be enforced to
     *                   match
     *                   path variable.
     * @return 201 Created with the persisted CustomerAddress in body and Location
     *         header pointing to /api/customers/{id}/addresses.
     * @throws IllegalArgumentException if input is invalid.
     */
    @PostMapping("/{customerId}/addresses")
    public ResponseEntity<CustomerAddress> addInitialAddress(@PathVariable String customerId,
            @Valid @RequestBody CustomerAddress address) {
        // Refer to the PathVariable, avoid unsync with the body
        address.setCustomerId(customerId);
        CustomerAddress saved = createAccountService.addInitialAddress(address);
        return ResponseEntity
                .created(URI.create("/api/customers/" + customerId + "/addresses"))
                .body(saved);
    }

    @GetMapping("/{customerId}")
    public ResponseEntity<Customer> getCustomerById(@PathVariable String customerId) {
        return buildCustomerResponse(customerService.findCustomerById(customerId));
    }

    private ResponseEntity<Customer> buildCustomerResponse(Optional<Customer> customer) {
        return customer.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }
}
