package sg.com.aori.model;

import java.time.LocalDateTime;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.validation.constraints.*;


/*
 * * @author Simon Lei
 * * @date 2025-10-11
 * * @version 2.0
 * Update on the Returns entity to add some validations.
 */
@Entity
@Table(name = "returns")
public class Returns {

    public enum ReturnReason {
        Size_issue,
        Defective,
        Changed_mind,
        Other
    }

    public enum ReturnStatus {
        Requested, // Initial status
        Approved,
        Denied,
        Refunded,
        Exchange
    }

    // Validation Groups
    public interface OnCreate {}
    public interface OnUpdate {}

    @Id
    @Column(name = "return_id", length = 36, nullable = false)
    // Added: system-generated at creation → Requirement "must be empty at creation, must have value at update".
    @Null(groups = OnCreate.class, message = "Return code must be null when creating a new return.")
    @NotBlank(groups = OnUpdate.class, message = "Return code is required when updating a return.")    
    private String returnId; // FIX: Removed direct initialization
    
    @Column(name = "return_code", length = 30, nullable = false, unique = true)
    // Added: If returnCode is generated by the system, same as returnId rule; if passed by the front-end, switch to @NotBlank.
    @Null(groups = OnCreate.class, message = "Return code must be null when creating a new return.")
    @NotBlank(groups = OnUpdate.class, message = "Return code is required when updating a return.")
    private String returnCode;

    // Foreign Key string field
    @Column(name = "order_item_id", length = 36, nullable = false)
    // Added: Incoming parameter checksum: must be a UUID string; if you are not UUIDs, replace the regular with ^[0-9]+$.
    @NotBlank(message = "Order Item ID is required.")
    @Size(max = 36, message = "orderItemId too long")
    @Pattern(regexp = "^[a-fA-F0-9\\-]{36}$", message = "orderItemId must be a valid UUID format.")
    private String orderItemId;

    @Enumerated(EnumType.STRING)
    @Column(name = "reason", nullable = false)
    
    @NotNull(message = "Return reason is required.")
    private ReturnReason reason;

    @Enumerated(EnumType.STRING)
    @Column(name = "return_status", nullable = false)

    @NotNull(message = "returnStatus is required.")
    private ReturnStatus returnStatus;

    @Column(name = "created_at", updatable = false)
    
    @PastOrPresent(message = "createdAt must be in the past or present.")
    private LocalDateTime createdAt;

    // ManyToOne relationship to OrderItem
    // NOTE: This setup relies on the service/controller setting orderItemId string.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_item_id", insertable = false, updatable = false)
    private OrderItem orderItem;

    /**
     * JPA Callback method to set ID, creation timestamp, and initial status.
     */
    @PrePersist
    protected void onCreate() {
        // Centralize ID generation logic
        if (this.returnId == null) {
            this.returnId = UUID.randomUUID().toString();
        }

        this.createdAt = LocalDateTime.now();

        // Set initial status if not already set
        if (this.returnStatus == null) {
            this.returnStatus = ReturnStatus.Requested;
        }
    }

    // --- Constructors ---

    public Returns() {
    }

    public Returns(String returnCode, String orderItemId, ReturnReason reason, ReturnStatus returnStatus) {
        this.returnCode = returnCode;
        this.orderItemId = orderItemId;
        this.reason = reason;
        this.returnStatus = returnStatus;
    }

    // --- Getters and Setters ---

    public String getReturnId() {
        return returnId;
    }

    public void setReturnId(String returnId) {
        this.returnId = returnId;
    }

    public String getReturnCode() {
        return returnCode;
    }

    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode;
    }

    public String getOrderItemId() {
        return orderItemId;
    }

    public void setOrderItemId(String orderItemId) {
        this.orderItemId = orderItemId;
    }

    public ReturnReason getReason() {
        return reason;
    }

    public void setReason(ReturnReason reason) {
        this.reason = reason;
    }

    public ReturnStatus getReturnStatus() {
        return returnStatus;
    }

    public void setReturnStatus(ReturnStatus returnStatus) {
        this.returnStatus = returnStatus;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public OrderItem getOrderItem() {
        return orderItem;
    }

    public void setOrderItem(OrderItem orderItem) {
        this.orderItem = orderItem;
        // Optionally update the foreign key string if the object is set
        if (orderItem != null) {
            this.orderItemId = orderItem.getOrderItemId();
        }
    }

    @Override
    public String toString() {
        return "{" +
                "returnId='" + returnId + '\'' +
                ", returnCode='" + returnCode + '\'' +
                ", orderItemId='" + orderItemId + '\'' +
                ", reason=" + reason +
                ", returnStatus=" + returnStatus +
                ", createdAt=" + createdAt +
                '}';
    }
}